version: "3.9"

services:

  rabbitmq:
    #image: rabbitmq:3.10-management
    build:
      context: .
      dockerfile: rabbitmq-docker/dockerfile
    container_name: rabbitmq_3_10
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - othman_network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

networks:
  othman_network:



