FROM rabbitmq:3.10-management
RUN rabbitmq-plugins enable --offline rabbitmq_shovel rabbitmq_shovel_management
COPY rabbitmq_delayed_message_exchange-3.10.2.ez /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.10.2.ez
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange
